name: "Run nix flake check"

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          diagnostic-endpoint: ""
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@v4
        with:
          diagnostic-endpoint: ""
      - run: nix flake check --log-format raw-with-logs -L

env:
  FORCE_COLOR: 1
